name: 圈X脚本编辑器
options:
  bundleIdPrefix: com.quantumx.editor
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.4"
  projectFormat: Xcode 14.0
  createIntermediateGroups: true
targets:
  圈X脚本编辑器:
    type: application
    platform: iOS
    bundleId: com.quantumx.editor
    sources:
      - path: Sources
        excludes:
          - 共享扩展
      - Assets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: 圈X脚本编辑器
        CFBundleShortVersionString: "1.5.5"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - target: 共享扩展
  共享扩展:
    type: app-extension
    platform: iOS
    bundleId: com.quantumx.editor.share
    sources:
      - Sources/共享扩展
    info:
      path: Sources/共享扩展/Info.plist
      properties:
        CFBundleDisplayName: 导入到圈X脚本编辑器
        CFBundleShortVersionString: "1.5.5"
        CFBundleVersion: "1"
