name: 圈X脚本编辑器
options:
  bundleIdPrefix: com.quantumx.editor
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.4"
  projectFormat: Xcode 14.0
  createIntermediateGroups: true
targets:
  圈X脚本编辑器:
    type: application
    platform: iOS
    sources:
      - Sources
      - Assets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: 圈X脚本编辑器
        CFBundleShortVersionString: "0.9.9"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
